-- Forge Atlas — D1 Database Schema
-- Database: forge-core  (binding: DB)
--
-- Apply via: wrangler d1 execute forge-core --file=db/schema.sql
--
-- Tables:
--   debates            — AI debate session records
--   forum_threads      — Forum thread metadata (AI-generated + user)
--   moderation_logs    — Content moderation decisions
--   prompt_records     — Saved prompt templates and usage
--   ai_usage_records   — AI request tracking for observability
-- ---------------------------------------------------------------------------

PRAGMA journal_mode = WAL;

-- ---------------------------------------------------------------------------
-- Debate sessions
-- Stores structured debate transcripts generated by the debate engine.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS debates (
  id           TEXT PRIMARY KEY,              -- "debate-<timestamp>-<rand>"
  topic        TEXT NOT NULL,
  rounds       INTEGER NOT NULL DEFAULT 3,
  transcript   TEXT NOT NULL,                 -- JSON: { rounds: [...] }
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  user_id      TEXT                           -- optional: links to profile
);

CREATE INDEX IF NOT EXISTS idx_debates_created_at ON debates (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_debates_user_id    ON debates (user_id);

-- ---------------------------------------------------------------------------
-- Forum thread metadata
-- Lightweight index of forum threads — body stored in KV or inline.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS forum_threads (
  id           TEXT PRIMARY KEY,              -- "t-<timestamp>" or seeded id
  title        TEXT NOT NULL,
  category     TEXT NOT NULL DEFAULT 'general',
  author       TEXT NOT NULL DEFAULT 'anonymous',
  body         TEXT,                          -- nullable: fetched from KV if NULL
  tags         TEXT,                          -- JSON array: ["tag1","tag2"]
  reactions    TEXT,                          -- JSON object: {"fire":0,...}
  replies      INTEGER NOT NULL DEFAULT 0,
  pinned       INTEGER NOT NULL DEFAULT 0,    -- 0 = false, 1 = true
  ai_generated INTEGER NOT NULL DEFAULT 0,   -- 0 = false, 1 = true
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_forum_threads_category   ON forum_threads (category);
CREATE INDEX IF NOT EXISTS idx_forum_threads_created_at ON forum_threads (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_forum_threads_pinned     ON forum_threads (pinned DESC, created_at DESC);

-- ---------------------------------------------------------------------------
-- Moderation logs
-- Records content moderation decisions for audit and review.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS moderation_logs (
  id            TEXT PRIMARY KEY,             -- "mod-<timestamp>-<rand>"
  content_type  TEXT NOT NULL,                -- "post" | "reply" | "title"
  content_ref   TEXT,                         -- ID of the content item (optional)
  verdict       TEXT NOT NULL,                -- "safe" | "warn" | "flag"
  reason        TEXT,
  categories    TEXT,                         -- JSON array: ["spam","harmful",...]
  confidence    REAL NOT NULL DEFAULT 0.0,
  reviewed_by   TEXT NOT NULL DEFAULT 'atlas-moderator',
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_moderation_verdict    ON moderation_logs (verdict);
CREATE INDEX IF NOT EXISTS idx_moderation_created_at ON moderation_logs (created_at DESC);

-- ---------------------------------------------------------------------------
-- Prompt records
-- Stores generated and user-saved prompt templates.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS prompt_records (
  id         TEXT PRIMARY KEY,                -- "prompt-<timestamp>-<rand>"
  title      TEXT NOT NULL,
  prompt     TEXT NOT NULL,
  category   TEXT NOT NULL DEFAULT 'devops',
  source     TEXT NOT NULL DEFAULT 'user',   -- "user" | "atlas-ai"
  user_id    TEXT,
  uses       INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_prompt_records_category   ON prompt_records (category);
CREATE INDEX IF NOT EXISTS idx_prompt_records_user_id    ON prompt_records (user_id);
CREATE INDEX IF NOT EXISTS idx_prompt_records_created_at ON prompt_records (created_at DESC);

-- ---------------------------------------------------------------------------
-- AI usage records
-- Tracks AI requests for observability and future rate-limit enforcement.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_usage_records (
  id          TEXT PRIMARY KEY,               -- "usage-<timestamp>-<rand>"
  route       TEXT NOT NULL,                  -- e.g. "/api/atlas/chat"
  agent_id    TEXT,                           -- e.g. "atlas-core"
  model       TEXT,                           -- e.g. "gpt-4o-mini"
  tokens_used INTEGER,
  latency_ms  INTEGER,
  status      TEXT NOT NULL DEFAULT 'ok',    -- "ok" | "error" | "rate_limited"
  user_id     TEXT,
  client_ip   TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_route      ON ai_usage_records (route);
CREATE INDEX IF NOT EXISTS idx_ai_usage_created_at ON ai_usage_records (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_agent_id   ON ai_usage_records (agent_id);
